### PR TITLE
Spark Spell

### PR DESCRIPTION
**Pull request by hexonaut**
Tooling up for Spark Spell process as well as some other cleanup. Includes spell for June 7th which does the following:

 * Maker pause proxy will give pool admin access to the Spark Proxy
 * Maker pause proxy executes the spells in here which does two things: Onboard rETH and update DAI interest rate strategy

### CODE REVIEW

**Comment by hexonaut** [comment]
This is ready for review now.

**Comment by hexonaut** [comment]
Goerli spell is setup which will execute this: https://github.com/makerdao/spells-goerli/pull/203

**Comment by amusingaxl** [comment]
I don't have access to this repo.

I didn't have the time to deep dive into Spark, but as far as it concerns [makerdao/spells-goerli #202](https://github.com/makerdao/spells-goerli/pull/202), it looks fine.

✅

**Comment by lucas-manuel** [comment]
Reviewed recent changes and pushed a formatting commit, LGTM.

**Comment by hexonaut** [comment]
Will merge this after spell is finished.

**Comment by hexonaut** [comment]
Actually going to merge now as this is blocking and the spell is all but published at this stage. If any changes come up can be PRed in a new one.

**Pull request merged**
